//
// Generated file, do not edit! Created by opp_msgtool 6.0 from packet.msg.
//

#ifndef __PACKET_M_H
#define __PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Packet;
/**
 * Class generated from <tt>packet.msg:17</tt> by opp_msgtool.
 * <pre>
 * packet Packet
 * {
 *     int streamId;	 // 所属流id
 *     int idx;		 // 包的idx信息
 *     bool isParity;	 // 是否是编码块
 *     double sendTime; // 流的发送时间
 * }
 * </pre>
 */
class Packet : public ::omnetpp::cPacket
{
  protected:
    int streamId = 0;
    int idx = 0;
    bool isParity_ = false;
    double sendTime = 0;

  private:
    void copy(const Packet& other);

  protected:
    bool operator==(const Packet&) = delete;

  public:
    Packet(const char *name=nullptr, short kind=0);
    Packet(const Packet& other);
    virtual ~Packet();
    Packet& operator=(const Packet& other);
    virtual Packet *dup() const override {return new Packet(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getStreamId() const;
    virtual void setStreamId(int streamId);

    virtual int getIdx() const;
    virtual void setIdx(int idx);

    virtual bool isParity() const;
    virtual void setIsParity(bool isParity);

    virtual double getSendTime() const;
    virtual void setSendTime(double sendTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Packet& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Packet& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Packet *fromAnyPtr(any_ptr ptr) { return check_and_cast<Packet*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PACKET_M_H

